site_name: Rappalini
site_description: Pablo Rappalini
site_author: Pablo Rappalini
site_url: https://rappalini.com.ar

theme:
  name: cinder # otros temas: mkdocs - readthedocs - material
  logo: images/logo.png
#  favicon: images/logo.png
  favicon: images/favicon_io/favicon.ico
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: grey
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: black
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.instant
    - toc.integrate
    - content.code.copy

nav:
  - Inicio: index.md
  - Proyectos:
      - Infraestructura: proyectos/infra.md
      - Seguridad: proyectos/sec.md
  - Sobre mí: about.md
  - Contacto: contacto.md
  - Data: mkdocs-commands.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

# Extra (favicon, logo, etc.)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prappalini
    - icon: fontawesome/solid/envelope
      link: mailto:rappalini@gmail.com
#      link: mailto:pablo@rappalini.com.ar
